[database]
url = "sqlite:///data/output/oxytcmri_database.db"
overwrite_data = true

[paths]
DTIDataPath = "data/input/MRI/DTI"
StructuralDataPath = "data/input/MRI/structural"
SubjectsList = "data/input/clinical_data/subjects_list.csv"
MDLesionsCSV = "data/output/results/oxytcmri_results.csv"
ClinicalData = "data/input/clinical_data/clinical_data.xlsx"
PbtO2Data = "data/input/clinical_data/PbtO2.csv"
IGS2Data = "data/input/clinical_data/Oxy-TC_Extraction_donnees_globales_20230324.xlsx"
ProcessedMRIFolder = "data/input/MRI/processed_mri"

[logs]
LogsDirectoryPath = "logs"
LogsFileName = "oxytcmri.log"

[brainlocalizers]
brain_localizers_list_json_path = "data/input/MRI/ROIs/brain_localizers_list.json"

[statanalysis]
additional_variables = [
    "glasgow_coma_scale",
    "marshall_score",
    "IGS2",
    "bilaterality_index_7_94",
    "sum_MD_lesions_in_mL_7_94_thalami",
    "sum_MD_lesions_in_mL_7_94_corpus_callosum",
    "sum_MD_lesions_in_mL_7_94_cerebral_white_matter",
    "dose_PIC_temps_prct",
    "trait_niv_3_r",
    "bl_reac_pupill_r",
    "pupil_abnormality"
]
statistics_excel_output_path = "data/output/results/oxytcmri_statistical_analysis_results.xlsx"
