[database]
path = "data/output/oxytcmri_clean_architecture_database.db"
url = "sqlite:///data/output/oxytcmri_database.db"
overwrite_data = true

[paths]
DTIDataPath = "data/input/MRI/DTI"
StructuralDataPath = "data/input/MRI/structural"
SubjectsList = "data/input/clinical_data/subjects_list.csv"
MDLesionsCSV = "data/output/results/oxytcmri_results.csv"
ClinicalData = "data/input/clinical_data/clinical_data.xlsx"
PbtO2Data = "data/input/clinical_data/PbtO2.csv"
IGS2Data = "data/input/clinical_data/Oxy-TC_Extraction_donnees_globales_20230324.xlsx"
ProcessedMRIFolder = "data/input/MRI/processed_mri"
# For Clean Architecture refactored code
centers_list = "data/input/centers_list.csv"
atlases_list = "data/input/MRI/ROIs/atlases_list.csv"
nifti_files_folder = "data/input/MRI/NiftiFilesFolder"
normative_dti_values_list = "data/input/MRI/DTI_normative_values.csv"

[logs]
LogsDirectoryPath = "logs"
LogsFileName = "oxytcmri.log"

[brainlocalizers]
brain_localizers_list_json_path = "data/input/MRI/ROIs/brain_localizers_list.json"
