[database]
url = "sqlite:///test-data/test.db"

[paths]
DTIDataPath = "test-data/dti-data"
StructuralDataPath = "test-data/structural-data"
SubjectsList = "test-data/subjects_list.csv"
MDLesionsCSV = "test-data/results/MD_lesions.csv"
ClinicalData = "test-data/outcomes.xlsx"
PbtO2Data = "test-data/pbtO2.csv"
IGS2Data = "test-data/igs2.xlsx"

[logs]
LogsDirectoryPath = "test-data/logs"
LogsFileName = "oxytcmri-test_data.log"